[package]
name = "agenda-memory"
version = "0.1.0"
authors = ["Enrico Risa <enrico.risa@prima.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

agenda-domain= { path="../domain"}
async-trait = "0.1.49"